packages:
  # core library
  - passquito-cdk-construct
  # client library for JavaScript on a browser
  - passquito-client-js
  # example CDK app
  - cdk
  # example web app
  - app

# version of common dependencies
catalog:
  "@microsoft/api-documenter": ^7.26.19
  "@microsoft/api-extractor": ^7.52.3
  "@types/node": 20.7.1
  aws-cdk: 2.1007.0
  cargo-lambda-cdk: 0.0.33
  npm-run-all2: ^7.0.2
  rimraf: ^6.0.1
  rollup: ^4.39.0
  rollup-plugin-esbuild: ^6.2.1
  ts-jest: ^29.3.4
  ts-node: ^10.9.1
  typescript: ~5.2.2
