packages:
  - passquito-cdk-construct
  - passquito-client-js
  - cdk
  - app

catalog:
  '@microsoft/api-documenter': ^7.26.29
  '@microsoft/api-extractor': ^7.52.8
  '@types/node': 20.7.1
  aws-cdk: 2.1019.2
  cargo-lambda-cdk: 0.0.33
  npm-run-all2: ^7.0.2
  rimraf: ^6.0.1
  rollup: ^4.44.1
  rollup-plugin-esbuild: ^6.2.1
  ts-jest: ^29.4.0
  ts-node: ^10.9.2
  typescript: ~5.2.2
