packages:
  - passquito-cdk-construct
  - passquito-client-js
  - cdk
  - app

catalog:
  '@microsoft/api-documenter': 7.28.2
  '@microsoft/api-extractor': 7.55.2
  '@types/jest': ^30.0.0
  '@types/node': 24.10.7
  aws-cdk: 2.1100.3
  aws-cdk-lib: 2.234.1
  cargo-lambda-cdk: 0.0.36
  constructs: 10.4.4
  jest: ^30.2.0
  npm-run-all2: ^8.0.4
  rimraf: ^6.1.2
  rollup: ^4.55.1
  rollup-plugin-esbuild: ^6.2.1
  ts-jest: ^29.4.6
  ts-node: ^10.9.2
  typescript: 5.8.2
